### ISSUE TITLE
timer question

### ISSUE THREAD

**Issue by hukuba** [siddii/angular-quiz-app#1]
looking your code, you have a timer. but I don't see it when I run the code.

what is the possible reason?

thanks.

**Comment by siddii** [comment]
The reason is `timer` directive isn't used.. If you add `<timer/>` on line #18 in index.html, you should see its working.

FYI - This timer directive in this app is the genesis of the angular timer module - http://siddii.github.io/angular-timer/

**Comment by siddii** [comment]
The reason I didn't add it by default in the first place is that, I use it for the presentation where I add it on the fly :)
